[14.0][ADD] account_move_vendor_ac_noins
solvosci/slv-account pull request #21
Opened 2023-01-19 11:35 UTC by adriresu

2023-01-19 11:35 UTC, adriresu commented
Tested locally, woks fine.

2023-01-19 19:07 UTC, dalonsod requested changes
At last, there's a non-covered case: when the purchase and vendor possible options is long enough, a "Search more..." is enabled, then a new wizard could be opened, and this wizard should also be restricted to POs:

![imagen](https://user-images.githubusercontent.com/12749832/213537228-2046b491-6ac8-4a54-9b98-058440c15bd8.png)


![imagen](https://user-images.githubusercontent.com/12749832/213537086-c7f39b78-b1ab-4753-83f1-0142560ec769.png)

Could you make the additional changes?

2023-01-20 10:49 UTC, dalonsod requested changes
Please attend comments

2023-01-20 10:49 UTC, dalonsod commented on account_move_vendor_ac_noinv/views/account_move_views.xml
> +        <field name="inherit_id" ref="account.view_move_form" />
This inheritance is wrong: this field doesn't exist in this view, in my test database fails indeed. In fact, purchase addon adds it. Could you check?

2023-01-20 10:49 UTC, dalonsod commented on account_move_vendor_ac_noinv/__manifest__.py
> +    "depends": ["account"],
Wrong inheritance:
```suggestion
    "depends": ["purchase"],
```

2023-01-24 17:31 UTC, dalonsod commented
In last force-push, only minor changes:
* Proper manifest category.
* Reword commit message

2023-01-24 17:31 UTC, dalonsod approved these changes
Let's merge it

2023-01-24 17:31 UTC, merged