[15.0][ADD] account_move_line_analytic_group
solvosci/slv-account pull request #40
Opened 2023-10-04 15:44 UTC by adriresu

2023-10-04 15:50 UTC, adriresu commented
Previous PR here:
https://github.com/solvosci/slv-account/pull/36

2023-10-05 17:25 UTC, dalonsod requested changes
Looks good, only two pending things!

2023-10-05 17:25 UTC, dalonsod commented on account_move_line_analytic_group/hooks.py
> +            SET analytic_account_group_id = COALESCE(subquery.group_id, NULL)
You should also add root group initialization (good luck with PostgreSQL split, I don't know if exists)

2023-10-05 17:25 UTC, dalonsod commented on account_move_line_analytic_group/views/account_move_line_views.xml
> +            </xpath>
Could you add search for group root?

2023-12-27 16:36 UTC, dalonsod approved these changes
Ready!

2023-12-27 16:36 UTC, merged