[13.0][ADD] account_invoice_date_maturity
solvosci/slv-account pull request #42
Opened 2024-01-17 16:24 UTC by ChristianSantamaria

Adds date_maturity field with Journal Entries action

2024-01-17 17:57 UTC, dalonsod requested changes
See comments... and I unhappily have to say that I don't agree with module name,,, better `account_move_line_date_maturity` , as it places in the right model. Sorry.

When comments are attended, please install it in AluTest environment.

cc @Anxo82

2024-01-17 17:57 UTC, dalonsod commented on account_invoice_date_maturity/views/account_move_views.xml
> +        <field name="context">{'default_type': 'entry', 'search_default_misc_filter':1}</field>
I'd emphasize that change in this way (setting value to `False`, and documenting original context):
```suggestion
        <!-- Overriden context: {'default_type': 'entry', 'search_default_misc_filter':1, 'view_no_maturity': True} -->
        <field name="context">{'default_type': 'entry', 'search_default_misc_filter':1, 'view_no_maturity': False}</field>
```

2024-01-17 17:57 UTC, dalonsod commented on account_invoice_date_maturity/__manifest__.py
> +        Adds date_maturity field with Journal Entries action
Better this (human readable field name, and right model name):
```suggestion
        Makes Due Date visible for Journal Items
```

2024-01-17 17:57 UTC, dalonsod commented on account_invoice_date_maturity/__manifest__.py
> +        "views/account_move_views.xml",
Action redefined in this file belongs to `account.move.line` model, so this file should be renamed.

2024-01-17 17:57 UTC, dalonsod commented on account_invoice_date_maturity/__manifest__.py
> +    "name": "Account Invoice Date Maturity",
Better this:
```suggestion
    "name": "Journal Item Due Date visible",
```

2024-01-18 07:00 UTC, dalonsod commented on account_invoice_date_maturity/__manifest__.py
> +        "views/account_move_views.xml",
Oops I was wrong, such action belongs to `account.move`. Forget it.

2024-01-18 07:02 UTC, dalonsod commented
> See comments... and I unhappily have to say that I don't agree with module name,,, better account_move_line_date_maturity , as it places in the right model. Sorry.

Nope! `account_move_date_maturity` , not `line`, but better than `invoice`.

2024-01-18 08:24 UTC, ChristianSantamaria commented
Instaled in Test Enviroment

2024-01-18 08:33 UTC, dalonsod commented
@lmiguens-solvos already installed in AluTest environment, could you check?

2024-01-18 11:22 UTC, lmiguens-solvos commented
LGTM, visto que ya sale la opción de seleccionar la fecha de vencimiento donde antes no salía
![image](https://github.com/solvosci/slv-account/assets/41901850/67f8c7f7-1110-41c2-9629-13c4457e05f4)

2024-01-18 14:49 UTC, dalonsod approved these changes
:+1:

2024-01-18 14:49 UTC, merged