[13.0][ADD] account_payment_promissory_note_partner_address
solvosci/slv-account pull request #57
Opened 2024-04-02 09:16 UTC by Anxo82

Allows to add payment partner address to promissory note.

2024-04-04 06:51 UTC, ChristianSantamaria commented
cc @dalonsod

2024-04-04 07:06 UTC, dalonsod requested changes
See comments

2024-04-04 07:06 UTC, dalonsod commented on account_payment_promissory_note_partner_address/report/payment_partner_address_template.xml
> +    <data noupdate="1">
With a template definition has no sense using `noupdate="1"`, remove it

2024-04-04 07:06 UTC, dalonsod commented on account_payment_promissory_note_partner_address/report/payment_partner_address_template.xml
> +            <xpath expr="//address[@t-field='o.partner_id']" position="attributes">
Is it possible to make original field invisible and add the new field, rather than replacing it?
If replace is finally needed, define the template with a low priority

2024-04-04 07:06 UTC, dalonsod commented on account_payment_promissory_note_partner_address/views/account_payment_views.xml
> +                <field name="payment_partner_id"/>
Check when this field should be modified, depending on e,g. payment state.
This field actually replaces `partner_id`... and according to

https://github.com/odoo/odoo/blob/4cc086d330b73514fbc64a7fcf22d8a7a9f1b691/addons/account/models/account_payment.py#L67

`partner_id` can only be modified in `draft` state. This seems to be very restricted, but making it always editable is too permissive. Please ask LR

2024-04-05 08:35 UTC, Anxo82 reviewed
See comments

2024-04-05 08:35 UTC, Anxo82 commented on account_payment_promissory_note_partner_address/models/account_payment.py
Change api_depends to api_onchange because if because in the draft state, payment_partner_id dont  saved.

2024-04-05 08:35 UTC, Anxo82 commented on account_payment_promissory_note_partner_address/report/payment_partner_address_template.xml
Finally, define the template with a low priority because if original field invisible and add the new field, not print payment_partner_id in report.

2024-04-05 08:37 UTC, dalonsod commented on account_payment_promissory_note_partner_address/models/account_payment.py
This seems to be incorrect, the field must be onchange or depends. Please try this:
- Take method back to depends.
- In view, add `force_save="1"` to the field definition

2024-04-05 08:39 UTC, dalonsod commented on account_payment_promissory_note_partner_address/report/payment_partner_address_template.xml
Very strange, I'll take a look at it with you. And priority must be defined in `<template>` node

2024-04-09 07:12 UTC, dalonsod approved these changes

2024-04-09 07:13 UTC, merged