[13.0][IMP] account_invoice_mgmt_dms: add merge compression
solvosci/slv-account pull request #64
Opened 2024-06-24 07:38 UTC by ChristianSantamaria

add merge compression

ghostscript

2024-06-24 08:59 UTC, dalonsod commented
:+1: please update `README.rst/index.html` files

2024-09-03 16:03 UTC, dalonsod requested changes
See comments

2024-09-03 16:03 UTC, dalonsod commented on account_invoice_mgmt_dms/models/stock_move.py
> +            record.carrier_doc_count = len(self.env['dms.file'].search([("proceeding", "=", record.picking_id.name), ("directory_id", "=", directory_id)]))
Was this a previous bug that is fixed here? If I'm right, please separate it in a previous and standalone commit

2024-09-03 16:03 UTC, dalonsod commented on account_invoice_mgmt_dms/models/dms_file.py
> +        for record in self.filtered(lambda x: x.directory_id == directory_id):
If we use `raise_if_not_found=True`, `directory_id` could be empty, so an `if` statement previous `for` statement could be added, and `for` skipped if directory is not found.

Anyway, carrier doc directory XML Id should be always accessed, because we cannot delete it (https://github.com/solvosci/slv-account/blob/5fa2f26118ff32be57508c95178674060c56c9c9/account_invoice_mgmt_dms/models/dms_directory.py#L11-L28)

2024-09-03 16:03 UTC, dalonsod commented on account_invoice_mgmt_dms/models/dms_file.py
> +            move_id = self.env['stock.move'].search([('picking_id.name', '=', record.proceeding)])
Please check if every user that can delete a file have read and write access to `stock.move` model (e.g. a DMS user). if not, please use `sudo()`.

2024-09-03 16:03 UTC, dalonsod commented on account_invoice_mgmt_dms/migrations/13.0.1.9.0/post-migration.py
> +        AND dms_file.proceeding IS NOT NULL;""",
Using a subselect could be expensive. Not sure if this alternative will work, but could you check?
```suggestion
        f"""
        UPDATE
	        stock_move
        SET
	        with_doc = true
        FROM
	        stock_move sm
        INNER JOIN
	        stock_picking sp on sp.id=sm.picking_id
        INNER JOIN
	        dms_file df on df.proceeding=sp.name
	        and df.directory_id = {directory_id.id}
        WHERE
	        stock_move.id=sm.id
        ;""",
```

2024-09-13 09:53 UTC, ChristianSantamaria commented
Done :+1: 
I'm going to leave this PR separate for ghostscript
New pr #68

2024-11-11 12:54 UTC, dalonsod requested changes
See comments. It looks good anyway

2024-11-11 12:54 UTC, dalonsod commented on account_invoice_mgmt_dms/views/account_move_views.xml
> +                    context ="{'validate': True}"
Remove unneeded space between attribute name and value. And, also, context variable name should be more specific, as context is a very general variable container for Odoo:
```suggestion
                    context="{'create_dms_file_document_validate': True}"
```

2024-11-11 12:54 UTC, dalonsod commented on account_invoice_mgmt_dms/models/account_move.py
> +        validate=self.env.context.get('validate',False)
According to previous comment, required change:
```suggestion
        validate = self.env.context.get('create_dms_file_document_validate', False)
```
And proper code formatting

2024-11-11 12:54 UTC, dalonsod commented on account_invoice_mgmt_dms/models/account_move.py
> +            "-dNOPAUSE", "-dBATCH", "-dSAFER","-dPDFSETTINGS=/ebook",
Is there are link in internet for `/ebook` setting addition, that can be used as explanation?

2024-11-11 12:56 UTC, dalonsod commented on account_invoice_mgmt_dms/README.rst
> +    :target: https://github.com/solvosci/slv-account/tree/15.0/account_invoice_mgmt_dms
README stuff seems to be generated with a wrong target version (15.0), please fix it @ChristianSantamaria

2024-11-11 16:41 UTC, DantePereyra commented
Changes done.

2024-11-19 18:23 UTC, dalonsod commented
@ChristianSantamaria could you add @DantePereyra as contributor of this addon. Once done, I'll merge it!

2024-11-20 11:09 UTC, dalonsod approved these changes
Let's merge!

2024-11-20 11:09 UTC, merged