[13.0][ADD] account_financial_report_menu
solvosci/slv-account pull request #65
Opened 2024-06-28 08:25 UTC by ChristianSantamaria

Change the menu position "Invoicing/Reports/OCA accounting reports" to "Invoicing/OCA accounting reports"

2024-06-28 12:17 UTC, ChristianSantamaria commented
@dalonsod how do you see it?

2024-06-28 12:18 UTC, dalonsod commented
:+1: could you install it in AluTest environment?

2024-06-28 12:30 UTC, ChristianSantamaria commented
Done :+1:

2024-07-03 09:30 UTC, dalonsod requested changes
See comments.
And also, could you try unistalling addon e.g. in your Dev environment and check if menu is restored to original place? If not, could you try an uninstall hook in order to get back original parent menu? See https://github.com/OCA/sale-workflow/blob/4227c9f2b9e4fbde8b2e3f2867cf0756cf248394/portal_sale_personal_data_only/hooks.py#L15

2024-07-03 09:30 UTC, dalonsod commented on account_financial_report_menu/__manifest__.py
> +        "account_financial_report",
Please add to `oca_dependencies.txt` a reference to `account-financial-reporting`.

2024-07-04 09:54 UTC, ChristianSantamaria commented
Done :+1:

2024-07-04 10:02 UTC, ChristianSantamaria commented
Miss oca_dependencies.. now its done

2024-07-04 10:32 UTC, dalonsod approved these changes
LGTM,

We'll actually install it as a beta development, because we are not 100% secure about read permissions of every Invoice user for every report (only General Ledger is validated).

2024-07-04 10:32 UTC, merged