[13.0][ADD] account_security_extra_oca
solvosci/slv-account pull request #73
Opened 2024-12-05 09:02 UTC by IriaAlonso

- Change the menu position "Invoicing/Configuration/Payment Mode" to "Invoicing/Accounting/Management/Payment Mode"
- In group Account User adds write and create permission to account.payment.mode 

@dalonsod

2024-12-05 09:13 UTC, dalonsod commented on account_security_extra_oca/__manifest__.py
> +    "license": "LGPL-3",
Wrong license (account_payment_mode has AGPL-3, and we have to respect it)

2024-12-05 09:22 UTC, IriaAlonso commented
@dalonsod change done

2024-12-05 09:25 UTC, dalonsod requested changes
Still missing changes in license in `hooks.py` and generated `README` stuff

2024-12-05 09:29 UTC, IriaAlonso commented
@dalonsod done

2024-12-05 09:30 UTC, dalonsod commented
Great!
@ChristianSantamaria could you also install this in AluTest enviroment, along with #72 ?

2024-12-09 06:26 UTC, ChristianSantamaria commented
Done :+1:

2024-12-09 13:10 UTC, dalonsod commented
Major changes made:
* ACL moved from "Show full account features" group to "Invoice" group (see ticket requirements).
* Updated ACL id and fixed typo in ACL name.

2024-12-09 13:10 UTC, merged